import pyttsx
engine = pyttsx.init()
engine.setProperty('rate', 150)

voices = engine.getProperty('voices')
print len(voices)
for voice in voices:
    print "Using voice:", repr(voice)
    engine.setProperty('voice', voices[1].id)
    engine.say("Hello")
    engine.setProperty('voice', voices[0].id)
    engine.say("Hi")
    engine.setProperty('voice', voices[1].id)
    engine.say("It's me")
    engine.setProperty('voice', voices[0].id)
    engine.say("Okay")
    engine.setProperty('voice', voices[1].id)
    engine.say("I was wondering")
    engine.setProperty('voice', voices[0].id)
    engine.say("About what?")
    engine.setProperty('voice', voices[1].id)
    engine.say("If after all these years you'd like to meet, to go over, everything")
    engine.setProperty('voice', voices[0].id)
    engine.say("Sure")
    engine.setProperty('voice', voices[1].id)
    engine.say("They say that time's supposed to heal yeah")
    engine.setProperty('voice', voices[0].id)
    engine.say("Cool")
    engine.setProperty('voice', voices[1].id)
    engine.say("But I ain't done much healing")
    engine.setProperty('voice', voices[0].id)
    engine.say("Too bad")
    engine.setProperty('voice', voices[1].id)
    engine.say("Violet Bingo Sausage Cream")
    engine.setProperty('voice', voices[0].id)
    engine.say("What the hell?")
engine.runAndWait()